manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: m165437
      url-base: https://github.com/M165437
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: cirque-input-module
      remote: oleksandrmaslov
      revision: absolute_mode
      path: modules/cirque-input-module

    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: zmk-input-gestures
      remote: oleksandrmaslov
      revision: main
    - name: zmk-input-processors
      remote: oleksandrmaslov
      revision: main
  self:
    path: config
